# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Web Accessibility Initiative (WAI)"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Website of the World Wide Web Consortium’s Web Accessibility Initiative.
baseurl: "/wai-coga-design-guide" # the subpath of your site, e.g. /blog
url: "https://w3c.github.io" # the base hostname & protocol for your site
twitter:
  username: w3c_wai
author: w3c_wai
exclude:
  - "_external"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "w3c.json"

# Build settings
markdown: kramdown
kramwdown:
  toc_levels: 2..3
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
repository: w3c/wai-coga-design-guide

ytkey: AIzaSyCiZ9uToWu9jb7BTx47NtzCvmGGXKXp8nI

remote_theme: w3c/wai-website-theme

permalink: pretty

collections_dir: content
collections:
  patterns:
    title: Patterns
    permalink: /:collection/:name/
    output: true
  objectives:
    title: Objectives
    permalink: /:collection/:name/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: standalone_resource
      lang: en   # Change "en" to the translated-language shortcode from https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
      last_updated: 2021-@@-@@   # Put the date of this translation YYYY-MM-DD (with month in the middle)
      github:
        repository: w3c/wai-coga-design-guide
      license: creative-commons   # NEW: delete if not creative-commons
      feedbackmail: wai@w3.org  # NEW: delete this line if it’s an EOWG resource (the default is wai-eo-editors@w3.org)
      footer: >   # Translate words below, including "Date:" and "Editor:" Translate the Working Group name. Leave the Working Group acronym in English. Do *not* change the dates in the footer below.
        <p><strong>Date:</strong> Updated @@ Month 2021. First published Month 20@@.</p>
        <p><strong>Editors:</strong> @@name, @@name. <strong>Contributors:</strong> @@name, @@name, and <a href="https://www.w3.org/groups/wg/@@wg/participants">participants of the @@WG</a>. ACKNOWLEDGEMENTS lists contributors and credits.</p>
        <p>Developed by the @@ Working Group (<a href="http://www.w3.org/WAI/@@/">@@WG</a>). Developed as part of the <a href="https://www.w3.org/WAI/@@/">WAI-@@ project</a>, @@co-funded by the European Commission.</p>
  -
    scope: 
      path: ""
      type: "pages"
    values:
      permalink: /:path/:basename/
  -
    scope: 
      type: "patterns"
      path: "_patterns"
    values:
      type_of_guidance: Pattern        
  -
    scope: 
      type: "objectives"
      path: "_objectives"
    values:
      type_of_guidance: Objective        

standalone_resource_nav_links:
  - name: All Objectives
    ref: /objectives
  - name: All Patterns
    ref: /patterns
  - name: About this Design Guide
    ref: /about
standalone_resource_doc_name: Design Guide
standalone_resource_doc_name_sub: "for People with Cognitive Disabilities and Learning Difficulties"



plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-remote-theme
  - wai-website-plugin
