name: build-dg-and-commit-to-wai

# build the Design Guide web pages and commit any change to the wai-coga-design-guide repo
#
# Notes:
# - parameters can be set in the env section 
# - the source filename needs to be set in two places below
#  - in the on: trigger definition
#  - in env
# - A Personal Access Token (PAT) stored as a secret is required for the push to work
#   - Suggest this is set in a specific W3C account, rather a user account, so not accidently deleted
# - GitHub shows in the commit message a linkto the ACT repo commit

on: 
  workflow_dispatch:

jobs:
  build-design-guide:
    name: Build Design Guide
    runs-on: ubuntu-latest
    env:
      DESTINATION_REPO: w3c/wai-coga-design-guide
      DESTINATION_BRANCH: master
      COMMIT_MESSAGE: Add Design Guide from https://github.com/${{ github.repository }}/commit/${{ github.sha }}
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: this
          ref: steve-web-dg
          
      - name: Clone ${{ env.DESTINATION_REPO }} and copy ${{ env.SOURCE_FILENAME }}
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }} # add as PAT (https://github.com/settings/tokens) as a secret
        run: |
          echo "Cloning $DESTINATION_REPO git repository"
          git clone --single-branch --branch $DESTINATION_BRANCH "https://$API_TOKEN_GITHUB@github.com/$DESTINATION_REPO.git" webdg
          
      - name: Build Web Design Guide
        run: |
          cd this
          design-guide/generate.sh
          cd ..
          cp -r this/design-guide/_site/* webdg/

      - name: Commit and push
        run: |
          cd webdg
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          # check for changes with git diff-index to stop error
          git diff-index --quiet HEAD || git commit -m "$COMMIT_MESSAGE"
          
          echo "Push"
          git push origin --set-upstream "$DESTINATION_BRANCH"
